# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd

CREATING DATASET


In [3]:
age = np.random.randint(1 ,100 , 100)
sal = np.random.randint(500, 8000,100)

array([7256, 3963, 2171, 5669, 3815, 1684, 4162, 7059, 3777, 1640,  894,
       3357, 5483, 5980, 3372, 4166, 5233, 3060, 7644, 6835, 2860,  729,
       2895, 2507, 3994, 3040, 5040, 7263, 2148, 2861, 1749, 2263, 4703,
       3070, 6615, 1824, 5250, 7705, 5673, 1565, 6344, 2904, 1036, 2013,
       4334, 6086, 4988, 1981, 1325, 7897, 4894, 5786, 2440, 1070, 5624,
       7243, 3413, 3335, 4912, 5739, 7430, 6052, 7971, 6022, 7497, 1981,
       6719, 2055, 2252, 5718, 2709,  884, 2159, 4046, 1553, 5755, 7610,
       2045, 7479, 6500, 4102, 3054, 6482, 2907, 6658, 7881, 3999, 2524,
       7915, 7403, 7849, 6356,  697, 4519, 6232, 4002, 6068, 5967, 6251,
       3586])

In [4]:
df = pd.DataFrame({"AGE" :age , "SALARY" :sal })
df

AGE  SALARY
0    31    7256
1     1    3963
2    16    2171
3    65    5669
4    47    3815
..  ...     ...
95   94    4002
96    5    6068
97   98    5967
98   49    6251
99   57    3586

[100 rows x 2 columns]

In [6]:
df['PURCHASED'] = 0
df

AGE  SALARY  PURCHASED
0    31    7256          0
1     1    3963          0
2    16    2171          0
3    65    5669          0
4    47    3815          0
..  ...     ...        ...
95   94    4002          0
96    5    6068          0
97   98    5967          0
98   49    6251          0
99   57    3586          0

[100 rows x 3 columns]

In [7]:
df['PURCHASED'] = df.apply(lambda x: 1 if (6*x['AGE']+3*x["SALARY"]>18000)  else 0, axis=1)
print(df)


    AGE  SALARY  PURCHASED
0    31    7256          1
1     1    3963          0
2    16    2171          0
3    65    5669          0
4    47    3815          0
..  ...     ...        ...
95   94    4002          0
96    5    6068          1
97   98    5967          1
98   49    6251          1
99   57    3586          0

[100 rows x 3 columns]


In [8]:
#Introduce Error
print(df)
df['AGE'] =  df['AGE'] +np.random.randint(0 , 33, 100)
df['SALARY'] = df['SALARY'] +np.random.randint(500, 1000, 100)

df        

    AGE  SALARY  PURCHASED
0    31    7256          1
1     1    3963          0
2    16    2171          0
3    65    5669          0
4    47    3815          0
..  ...     ...        ...
95   94    4002          0
96    5    6068          1
97   98    5967          1
98   49    6251          1
99   57    3586          0

[100 rows x 3 columns]


AGE  SALARY  PURCHASED
0    46    7766          1
1     6    4560          0
2    28    2901          0
3    71    6196          0
4    69    4588          0
..  ...     ...        ...
95  117    4995          0
96   28    6663          1
97  114    6833          1
98   52    6983          1
99   85    4439          0

[100 rows x 3 columns]


## Importing the dataset

In [9]:
df.to_csv("Record10.csv" , index = 0)

In [10]:
dataset = pd.read_csv('Record10.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
X

array([[  46, 7766],
       [   6, 4560],
       [  28, 2901],
       [  71, 6196],
       [  69, 4588],
       [  61, 2505],
       [  60, 4973],
       [  71, 7892],
       [   9, 4342],
       [  45, 2562],
       [  69, 1870],
       [  97, 4010],
       [  32, 6271],
       [  88, 6729],
       [ 111, 3885],
       [  85, 4841],
       [  25, 6160],
       [   4, 3672],
       [ 106, 8294],
       [  80, 7521],
       [  94, 3550],
       [  41, 1575],
       [  61, 3734],
       [ 105, 3471],
       [  80, 4496],
       [  95, 3844],
       [ 107, 5909],
       [  95, 8219],
       [   9, 2744],
       [  33, 3400],
       [  30, 2292],
       [  30, 3091],
       [ 103, 5400],
       [  75, 3847],
       [  80, 7157],
       [  48, 2511],
       [ 101, 6165],
       [  96, 8286],
       [ 111, 6417],
       [ 104, 2477],
       [  33, 7268],
       [  52, 3900],
       [  86, 1571],
       [  63, 2669],
       [  75, 4879],
       [   9, 7020],
       [ 100, 5659],
       [  90,

## Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [12]:
print(X_train)

[[  35 2001]
 [  60 4973]
 [  85 4439]
 [  54 6997]
 [  43 8135]
 [  51 8028]
 [ 104 5003]
 [  55 8581]
 [  36 3191]
 [  57 6364]
 [  95 8219]
 [ 106 8294]
 [  23 4233]
 [  50 6526]
 [  70 2307]
 [   6 4560]
 [ 117 6936]
 [  86 1571]
 [  52 3900]
 [  69 4588]
 [  85 4841]
 [   4 3672]
 [  33 7268]
 [ 111 6417]
 [  61 2505]
 [  89 6979]
 [  17 6342]
 [  46 7766]
 [  80 7157]
 [   9 2744]
 [  89 5752]
 [  97 4010]
 [  48 2511]
 [ 105 3471]
 [  22 3418]
 [  69 1870]
 [  30 3091]
 [  38 7696]
 [  54 4220]
 [ 111 7322]
 [  98 8861]
 [ 103 5400]
 [  82 7250]
 [ 111 3885]
 [  73 8049]
 [  80 7521]
 [  33 3400]
 [  67 8814]
 [ 114 6833]
 [  52 6983]
 [ 101 6369]
 [  94 3550]
 [  36 6982]
 [  56 3097]
 [  85 2680]
 [  95 3844]
 [  96 8286]
 [  71 3815]
 [ 100 5659]
 [ 104 2477]
 [  96 2506]
 [  45 5830]
 [  32 6271]
 [  93 8867]
 [  88 3537]
 [  45 3447]
 [ 101 6165]
 [  41 1575]
 [  78 3809]
 [  45 2562]
 [  28 6663]
 [  68 2891]
 [  18 8191]
 [  90 2838]
 [  75 4879]]


In [13]:
print(y_train)

[0 0 0 1 1 1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0
 1 0 1 1 0 1 0 1 1 0 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0
 0]


In [14]:
print(X_test)

[[ 107 5909]
 [  69 4740]
 [  28 2901]
 [  27 7783]
 [  89 6275]
 [  81 5068]
 [  25 6160]
 [  80 4586]
 [  90 6340]
 [ 117 4995]
 [  33 1676]
 [ 110 1396]
 [  37 8062]
 [  88 6729]
 [  71 7892]
 [  30 2292]
 [  61 3734]
 [  80 4496]
 [  75 3847]
 [   9 4342]
 [  63 2669]
 [  97 8767]
 [  71 6196]
 [  84 1859]
 [   9 7020]]


In [15]:
print(y_test)

[0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1]


## Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
print(X_train)

[[-1.08053076 -1.50901737]
 [-0.24368847 -0.1168508 ]
 [ 0.59315381 -0.3669911 ]
 [-0.44453062  0.83124648]
 [-0.81274123  1.36431699]
 [-0.5449517   1.31419525]
 [ 1.22915395 -0.10279798]
 [-0.41105693  1.57323566]
 [-1.04705707 -0.95158863]
 [-0.34410955  0.53473187]
 [ 0.92789073  1.4036649 ]
 [ 1.29610133  1.43879697]
 [-1.48221506 -0.46348716]
 [-0.57842539  0.61061712]
 [ 0.09104844 -1.36567855]
 [-2.05126781 -0.31031137]
 [ 1.66431194  0.8026724 ]
 [ 0.6266275  -1.7104412 ]
 [-0.51147801 -0.61947353]
 [ 0.05757475 -0.2971954 ]
 [ 0.59315381 -0.17868324]
 [-2.11821519 -0.726275  ]
 [-1.14747814  0.95819034]
 [ 1.46346979  0.55955852]
 [-0.21021478 -1.27292991]
 [ 0.72704858  0.82281479]
 [-1.68305721  0.52442646]
 [-0.71232015  1.19146724]
 [ 0.42578536  0.90619488]
 [-1.95084674 -1.16097573]
 [ 0.72704858  0.24805423]
 [ 0.99483811 -0.5679465 ]
 [-0.64537277 -1.27011934]
 [ 1.26262764 -0.82042893]
 [-1.51568875 -0.84525559]
 [ 0.05757475 -1.57038138]
 [-1.24789922 -0.99843138]
 

In [18]:
print(X_test)

[[ 1.32957502  0.32159735]
 [ 0.05757475 -0.22599441]
 [-1.3148466  -1.08743261]
 [-1.34832029  1.19943051]
 [ 0.72704858  0.49304182]
 [ 0.45925905 -0.07235019]
 [-1.41526767  0.43917265]
 [ 0.42578536 -0.29813225]
 [ 0.76052227  0.52348961]
 [ 1.66431194 -0.1065454 ]
 [-1.14747814 -1.66125631]
 [ 1.4299961  -1.79241602]
 [-1.01358338  1.33012178]
 [ 0.69357489  0.70570791]
 [ 0.12452213  1.25048911]
 [-1.24789922 -1.37270497]
 [-0.21021478 -0.69723249]
 [ 0.42578536 -0.34029073]
 [ 0.2584169  -0.64430018]
 [-1.95084674 -0.41242856]
 [-0.1432674  -1.19610779]
 [ 0.99483811  1.66036318]
 [ 0.12452213  0.45603604]
 [ 0.55968012 -1.57553408]
 [-1.95084674  0.84202031]]


## Training the Logistic Regression model on the Training set

In [19]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)


LogisticRegression(random_state=0)

## Predicting a new result

In [ ]:
print(classifier.predict(sc.transform([[45,6000]])))

## Predicting the Test set results

In [ ]:
X_test

In [ ]:
y_pred

In [ ]:
y_test

In [20]:
y_pred = classifier.predict(X_test)
#print(y_pred)
#print(y_pred.shape)
#print(y_pred.reshape(25,1))
#print(y_pred.reshape(len(y_pred),1))

#print(y_test.reshape(len(y_test),1))

print("Predict Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


Predict Actual
[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


In [ ]:
print("Pred Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


## Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print(cm)
accuracy_score(y_test, y_pred)

[[19  0]
 [ 0  6]]


1.0

In [ ]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


In [ ]:
len(y_pred)

In [ ]:
y_pred.shape

#1 row and 25 elements

#but what we want is   # 1 column  and 25 rows in it

In [ ]:
y_pred.reshape(len(y_pred),1)

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy is: " ,round(accuracy_score(y_test, y_pred),2)*100, "%")

In [ ]:
Train any algo

1. import the lib
2. create the object 
3. .fit() on training dataset
4. .predict() on test dataset